language: ruby
cache: bundler
rvm:
- ruby-head
- 2.2.0
- 2.1.0
- 2.0.0
- 1.9.3

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - bundle exec rspec
  - bundle exec rubocop

deploy:
  provider: rubygems
  api_key:
    secure: g7xKyeiMs2o1HLokzOWCiLKxmTaEmuQDB0he9kxFhjqMLbRQHu1pVL0uE2bD0K/zq8Ebb+OPchVmej/6s5Be97AOK5d1wGdBAhXISwlxPoXxLJ6zU5DF1vjF3YCZK197z81ATcGcocsD2eYXZ4NzJcI+FW3kzO6QQhfHfUUeHvM=
  gem: bwapi
  on:
    branch: staging
    repo: jonathanchrisp/bwapi
